config/routes.rb
Rails.application.routes.draw do
  get 'experimiento/index'

  get 'experimiento/formula'
  resources :experimentos

  resources :users

end

app/models/experimento.rb
class Experimento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def otra_funcion
    Rails.logger.info "Un mensaje"
  end
end

app/controllers/experimentos_controller.rb
class ExperimentosController < ApplicationController
  before_action :set_experimento, only: [:show, :edit, :update, :destroy]

  # GET /experimentos
  # GET /experimentos.json
  def index
    @experimentos = Experimento.all
  end

  # GET /experimentos/1
  # GET /experimentos/1.json
  def show
  end

  # GET /experimentos/new
  def new
    @experimento = Experimento.new
  end

  # GET /experimentos/1/edit
  def edit
  end

  # POST /experimentos
  # POST /experimentos.json
  def create
    @experimento = Experimento.new(experimento_params)

    respond_to do |format|
      if @experimento.save
        format.html { redirect_to @experimento, notice: 'Experimento was successfully created.' }
        format.json { render :show, status: :created, location: @experimento }
      else
        format.html { render :new }
        format.json { render json: @experimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experimentos/1
  # PATCH/PUT /experimentos/1.json
  def update
    respond_to do |format|
      if @experimento.update(experimento_params)
        format.html { redirect_to @experimento, notice: 'Experimento was successfully updated.' }
        format.json { render :show, status: :ok, location: @experimento }
      else
        format.html { render :edit }
        format.json { render json: @experimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experimentos/1
  # DELETE /experimentos/1.json
  def destroy
    @experimento.destroy
    respond_to do |format|
      format.html { redirect_to experimentos_url, notice: 'Experimento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experimento
      @experimento = Experimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experimento_params
      params.require(:experimento).permit(:apu)
    end
end

app/controllers/experimiento_controller.rb
class ExperimientoController < ApplicationController
  def index
  end

  def formula
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def validacion_especial
    true
  end

  def otra_validacion
    false
  end
end

app/helpers/experimentos_helper.rb
module ExperimentosHelper
end

app/helpers/experimiento_helper.rb
module ExperimientoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experimentos/_form.html.erb
<%= form_for(@experimento) do |f| %>
  <% if @experimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experimento.errors.count, "error") %> prohibited this experimento from being saved:</h2>

      <ul>
      <% @experimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apu %><br>
    <%= f.text_field :apu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experimentos/edit.html.erb
<h1>Editing experimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @experimento %> |
<%= link_to 'Back', experimentos_path %>

app/views/experimentos/index.html.erb
<h1>Listing experimentos</h1>

<table>
  <thead>
    <tr>
      <th>Apu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experimentos.each do |experimento| %>
      <tr>
        <td><%= experimento.apu %></td>
        <td><%= link_to 'Show', experimento %></td>
        <td><%= link_to 'Edit', edit_experimento_path(experimento) %></td>
        <td><%= link_to 'Destroy', experimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experimento', new_experimento_path %>

app/views/experimentos/new.html.erb
<h1>New experimento</h1>

<%= render 'form' %>

<%= link_to 'Back', experimentos_path %>

app/views/experimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apu:</strong>
  <%= @experimento.apu %>
</p>

<%= link_to 'Edit', edit_experimento_path(@experimento) %> |
<%= link_to 'Back', experimentos_path %>

app/views/experimiento/formula.html.erb
<h1>Experimiento#formula</h1>
<p>Find me in app/views/experimiento/formula.html.erb</p>

app/views/experimiento/index.html.erb
<h1>Experimiento#index</h1>
<p>Find me in app/views/experimiento/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pruebas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>